<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
      <ProjectReference Include="..\WebApplication3.Model\WebApplication3.Model.csproj" />
      <ProjectReference Include="..\WebApplication3.Repository.Common\WebApplication3.Repository.Common.csproj" />
    </ItemGroup>

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

</Project>
